name: Revyl Dummy → Publish pinned → Verify → Trigger tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dummy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    env:
      REVYL_API_KEY: ${{ secrets.REVYL_API_KEY }}
      VER: dummy-pr-${{ github.event.number }}-run-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout Revyl Actions
        uses: actions/checkout@v4
        with:
          repository: RevylAI/revyl-gh-action
          path: revyl-actions
          
      - name: Make tiny artifact
        run: dd if=/dev/urandom of=artifact.apk bs=1024 count=200
      
      - name: Upload to Revyl
        uses: ./revyl-actions/actions/upload-build
        with:
          build-var-id: ${{ vars.REVYL_BUILD_VAR_ANDROID }}
          version: ${{ env.VER }}
          file-path: artifact.apk
          backend-url: ${{ secrets.REVYL_BASE_URL }}
          metadata: |
            {
              "platform": "Android",
              "app_id": "com.revyl.dummy",
              "build_system": "dummy",
              "ci_run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "commit_sha": "${{ github.sha }}",
              "pr_number": ${{ github.event.number }},
              "branch": "${{ github.ref_name }}"
            }
      
      - name: Verify Resolution
        uses: ./revyl-actions/actions/verify-resolution
        with:
          build-var-id: ${{ vars.REVYL_BUILD_VAR_ANDROID }}
          version: ${{ env.VER }}
          backend-url: ${{ secrets.REVYL_BASE_URL }}
      
      - name: Trigger Tests (placeholder)
        run: |
          echo "✅ Would trigger test run with version: ${{ env.VER }}"
          echo "This step would use a trigger-test action when available"